version: '3.9'

services:
  books:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8001:80

  reviews:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8002:80

  books_db:
    ports:
      - 15432:5432

  reviews_db:
    ports:
      - 25432:5432

  rabbitmq:
    image: rabbitmq:3-management
