version: '3.9'

networks:
  ibdb-network:
    driver: bridge

volumes:
  ibdb-books-db-volume:
  ibdb-reviews-db-volume:

services:
  books:
    container_name: ibdb-books
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Ibdb.Books/Dockerfile
    environment:
      - CONNECTIONSTRINGS__BOOKS=Server=books_db;Port=5432;Database=books;User Id=books;Password=books
      - CONNECTIONSTRINGS__EVENTSTORE=Server=books_db;Port=5432;Database=books;User Id=books;Password=books
      - CONNECTIONSTRINGS__OUTBOX=Server=books_db;Port=5432;Database=books;User Id=books;Password=books
      - CONNECTIONSTRINGS__RABBITMQ=host=rabbitmq;username=rabbitmq;password=rabbitmq
    networks:
      - ibdb-network
    depends_on:
      - books_db
      - rabbitmq

  reviews:
    container_name: ibdb-reviews
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Ibdb.Reviews/Dockerfile
    environment:
      - CONNECTIONSTRINGS__REVIEWS=Server=reviews_db;Port=5432;Database=reviews;User Id=reviews;Password=reviews
      - CONNECTIONSTRINGS__EVENTSTORE=Server=reviews_db;Port=5432;Database=reviews;User Id=reviews;Password=reviews
      - CONNECTIONSTRINGS__OUTBOX=Server=reviews_db;Port=5432;Database=reviews;User Id=reviews;Password=reviews
      - CONNECTIONSTRINGS__RABBITMQ=host=rabbitmq;username=rabbitmq;password=rabbitmq
    networks:
      - ibdb-network
    depends_on:
      - reviews_db
      - rabbitmq

  migrator:
    container_name: ibdb-migrator
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Ibdb.Shared.Migrator/Dockerfile
    environment:
      - CONNECTIONSTRINGS__BOOKS=Server=books_db;Port=5432;Database=books;User Id=books;Password=books
      - CONNECTIONSTRINGS__EVENTSTORE=Server=books_db;Port=5432;Database=books;User Id=books;Password=books
    networks:
      - ibdb-network
    depends_on:
      - books_db

  books_db:
    container_name: ibdb-books-db
    image: postgres:14
    restart: unless-stopped
    networks:
      - ibdb-network
    environment:
      - POSTGRES_DB=books
      - POSTGRES_USER=books
      - POSTGRES_PASSWORD=books
    volumes:
      - ibdb-books-db-volume:/var/lib/postgresql/data

  reviews_db:
    container_name: ibdb-reviews-db
    image: postgres:14
    restart: unless-stopped
    networks:
      - ibdb-network
    environment:
      - POSTGRES_DB=reviews
      - POSTGRES_USER=reviews
      - POSTGRES_PASSWORD=reviews
    volumes:
      - ibdb-books-db-volume:/var/lib/postgresql/data

  rabbitmq:
    container_name: ibdb-rabbitmq
    restart: unless-stopped
    image: rabbitmq:3
    networks:
      - ibdb-network
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq